import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';

import { AppModule } from './app/app.module';
import { registerLicense } from '@syncfusion/ej2-base';


registerLicense('Mgo+DSMBaFt+QHJqVk1mQ1NNaV1CX2BZf1J8RWBTelxgBShNYlxTR3ZaQV1iSH5Qc0ZhX35Z;Mgo+DSMBPh8sVXJ1S0R+X1pCaV1LQmFJfFBmRGJTf116cVdWESFaRnZdQV1mSn5Sd0VgXHxcd31S;ORg4AjUWIQA/Gnt2VFhiQlJPcEBAVHxLflF1VWJYdV5zflBEcC0sT3RfQF5jTH1Td0RjWnpdcn1SQQ==;MjI1MDU5NUAzMjMxMmUzMDJlMzBneGhQSHo1c2grRGpnTFh4bW1leTJMbkpJSzJrdkZrNjRpQzgwZUFKMG9VPQ==;MjI1MDU5NkAzMjMxMmUzMDJlMzBncDhDSGE5bnR3OENjZjMxQlE5NmgwU2JHb1lwOG0yR2djQkRHNnpSV1Q4PQ==;NRAiBiAaIQQuGjN/V0d+Xk9HfVldX2pWfFN0RnNYflRwd19DYkwgOX1dQl9gSXtQdkRiWXxbc3dSRWc=;MjI1MDU5OEAzMjMxMmUzMDJlMzBGazVnNXZ3UkhXNmVqc2d0L2Z3clFmWFlmTnVtemNaMmZ6VDBpdDkvVURJPQ==;MjI1MDU5OUAzMjMxMmUzMDJlMzBoS0Fqb3VFZHdFUDRJYWpNOWFJVHA5QmtLbmltQ1Joc1ZYdFBiOURYUDlBPQ==;Mgo+DSMBMAY9C3t2VFhiQlJPcEBAVHxLflF1VWJYdV5zflBEcC0sT3RfQF5jTH1Td0RjWnpddHJTQQ==;MjI1MDYwMUAzMjMxMmUzMDJlMzBMV0NJK0xuMTVVRG1MdmVRRlg4MFdwbktYRzdudTRoMk13VlZWRnIzcTRnPQ==;MjI1MDYwMkAzMjMxMmUzMDJlMzBMM3NqS0xWejdnVVl0WEwwSFdyakNQWGVobW56Rmc5dWJCY1l1ekxzRDFvPQ==;MjI1MDYwM0AzMjMxMmUzMDJlMzBGazVnNXZ3UkhXNmVqc2d0L2Z3clFmWFlmTnVtemNaMmZ6VDBpdDkvVURJPQ==');
platformBrowserDynamic().bootstrapModule(AppModule)
  .catch(err => console.error(err));
